import {
  Globe,
  Book,
  ShoppingCart,
  MessageSquare,
  Clock,
  Smartphone,
} from "lucide-react";

import { projectProps } from "../ProjectProps";

export const projects: projectProps[] = [
  {
    id: 1,
    title: "Portfolio - Website App",
    desc: "A modern personal portfolio built with Next.js & Tailwind CSS.",
    tech: ["Next.js 14", "TypeScript", "Tailwind CSS", "OpenAI GPT-4.1"],
    features: [
      "Chatbot Agent",
      "Dark mode",
      "Responsive design",
      "SEO optimization",
    ],
    deployment: "Deployed on Vercel",
    year: "2025",
    url: "/",
    icon: Book,
  },
  {
    id: 2,
    title: "Assessify - Mobile App (Currently in Development)",
    desc: "SmartReviewr – AI-powered study and quiz generator.",
    tech: ["React Native", "Cli", "OpenAI API", "Firebase", "OCR"],
    features: [
      "DOCS, PDF, IMAGES, Scan or uploads",
      "AI-generated quizzes",
      "Download Quizes",
      "Cloud sync",
    ],
    deployment: "MVP Prototype",
    year: "2025",
    url: "/",
    icon: Globe,
  },
  {
    id: 3,
    title: "Badminton Queuing Management System - (Capstone)",
    desc: "Full-stack MERN app for Badminton Queuing",
    tech: [
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.io",
      "Tailwind CSS",
    ],
    features: [
      "Player queuing",
      "Payment integration",
      "Product & booking management",
    ],
    deployment: "Deployed on Hostinger(VPS) - but Expired & Vercel - Lived",
    year: "2024",
    url: "/",
    icon: ShoppingCart,
  },
  {
    id: 4,
    title: "DealWise",
    desc: "Affiliate shop app that helps you find the best deals quickly.",
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "Node.js",
      "MongoDB",
      "Cloudinary",
      "OpenAI GPT-4.1",
    ],
    features: [
      "Admin dashboard with secure authentication",
      "Responsive comparison UI",
      "Personalized deal alerts",
    ],
    deployment: "Deployed on Vercel",
    year: "2025",
    url: "https://deal-wise.vercel.app/",
    icon: Smartphone,
  },
  {
    id: 5,
    title: "Lootify - E-Commerce Web App",
    desc: "AI-powered chatbot with real-time response handling.",
    tech: ["React", "Firebase", "Node.js"],
    features: [
      "Real-time chat assistant",
      "E-commerce product management",
      "Order tracking",
    ],
    deployment: "Deployed on Netlify",
    year: "2024",
    url: "/",
    icon: Clock,
  },
  {
    id: 6,
    title: "Gadgetary Solution - Web App(Static)",
    desc: "A school project ",
    tech: ["React", "Redux Toolkit", "Tailwind CSS"],
    features: [
      "Drag-and-drop",
      "Task categorization",
      "Reminders",
      "Progress tracking",
    ],
    deployment: "Deployed on Render - Static",
    year: "2023",
    url: "/",
    icon: MessageSquare,
  },
];
